[build]
  command = "chmod +x ./node_modules/.bin/vite && ./node_modules/.bin/vite build"
  publish = "dist/client"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"