/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// It was generated by running `npx tsr generate` or `npx tsr watch`.
// Do NOT edit this file manually.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes
import { Route as rootRoute } from './routes/__root'
import { Route as PropietariosRoute } from './routes/propietarios'
import { Route as LoginRoute } from './routes/login'
import { Route as FaturacionRoute } from './routes/facturacion'
import { Route as TratamientosRoute } from './routes/tratamientos'
import { Route as DashboardRoute } from './routes/dashboard'
import { Route as CitasRoute } from './routes/citas'
import { Route as IndexRoute } from './routes/index'

// Create/Update Routes
const PropietariosRouteWithChildren = PropietariosRoute
const LoginRouteWithChildren = LoginRoute
const FacturacionRouteWithChildren = FaturacionRoute
const TratamientosRouteWithChildren = TratamientosRoute
const DashboardRouteWithChildren = DashboardRoute
const CitasRouteWithChildren = CitasRoute
const IndexRouteWithChildren = IndexRoute

// Generate route tree
export const routeTree = rootRoute.addChildren([
  IndexRouteWithChildren,
  LoginRouteWithChildren,
  DashboardRouteWithChildren,
  PropietariosRouteWithChildren,
  CitasRouteWithChildren,
  TratamientosRouteWithChildren,
  FacturacionRouteWithChildren,
])

export type RootRoute = typeof rootRoute
